title: Zijian
url: "https://zijian0615.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://zijian0615.github.io"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
