title: Zijian
url: "https://zijian0615.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url:"zjzhang2023@hkbu.edu.hk" 
footer_text: "zjzhang2023@hkbu.edu.hk"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Resume"
   link: "Vitae_Zijian.pdf"
 - name: "Research"
   link: "research"
 - name: "Recreation"
   link: "contact"
